### ISSUE TITLE
スキーマ定義

### ISSUE THREAD

**Issue by Ta23ka98** [Ta23ka98/life_snap#24]
## 概要

・Dart/Firebaseのスキーマ定義をする。

## 要件

・どんなスキーマにするか議論
・スキーマをymlファイルで定義
・スキーマ図の作成

**Comment by Ta23ka98** [comment]
MTGのメモ：
今回のアプリに必要そうなフィールドは...

・テキスト
・経度/緯度の座標(マップのピン/ARカメラのオブジェクト表示用)
・画像のパス
・ユーザID
・投稿するID
・ユーザ名
・いいね数

**Comment by Ta23ka98** [comment]
@hirom0922 
MTGで仰っていた、スキーマ定義に関する記事を教えて頂きたいです🙇

**Comment by hirom0922** [comment]
この辺りです。
https://qiita.com/PictoMki/items/f04e205f6eb45ed9c5bf
https://qiita.com/PictoMki/items/52012bf222de1b0440cc

**Comment by ke158** [comment]
最低限いるUSERのスキーマです。

      USER
      String? id,           //ユーザーのuid
      required　String userId,  //@user_id
      required　String userName, //ユーザー名                       
      @Default('') String selfIntroduction,      //紹介文
      required String profileImageURL,  //ユーザーの画像
      @CreatedAtField() DateTime? createdAt, 登録日時　 //@CreatedAtField() timestampとDateTimeの変換処理
    
FirebaseのサブコレクションにmyPost（自分の投稿）
    postId　自分が投稿したID
   createdAt 作成日時
    
   FirebaseのサブコレクションにmyLike（自分がいいねをした投稿）
likeId　自分がいいねをした投稿ID
   createdAt　いいねをした日時

フォロワー機能があれば追加でサブコレクションに追加

**Comment by ke158** [comment]
最低限いるPostスキーマ
    String? id,　　　　　// 投稿uid
    required　String postUserId,　// ユーザーのuid
    required　String postImage, // 投稿画像
    required　String title,            // タイトル
    required　String content,     // 投稿内容
    required　○○　　　　　　//緯度経度
    @Default(0) int likeCount, // like数
    @CreatedAtField() DateTime? createdAt, //投稿日時

参考程度に見ておいてください

**Comment by Ta23ka98** [comment]
@hirom0922  @ke158 
ありがとうございます🙌
一通り確認させて頂きました！

この辺りはMTGで話し合う方がいいかもですね🤔

**Comment by hirom0922** [comment]
まさたかさんのをベースに物理構造を少し考えてみました。

likeの管理ってFirebaseの場合は、最適解って何だろうというのが、
あります。
自分のlike消したい場合、Documentの１M制限を考えて、
like数と管理を別にしてみたのですが、実装してみないと分かりません。。。

参考のPGに倣いまして、documentid=idなのですが、こちらもやってみる中で、
別項目として必要なのか見てみたいです。

users: #collection
  documentId: # userId = auth.uid
    id: string # document Id
    userName: string
    selfIntroduction: string
    profileImageURL: string
    createdAt: timestamp

posts: #collection
  documentId: # auto
    id: string # document Id
    postUserId: reference
    postImageURL: string
    title: string
    content: string
    postGeopoint: geopoint
    likeCount: number
    createdAt: timestamp

userLikes: #collection
  documentId: # auto
    id: string # document Id
    userId: reference
    postId: reference
    createdAt: timestamp

**Comment by hirom0922** [comment]
@ke158 @Ta23ka98 
こちらの方が良いかな。
    ＃postGeopoint: geopoint
    ↓
    postPosition:
  （スペース）geohash: string
  （スペース）geopoint: geopoint

ご参考：
  https://zenn.dev/wakanao/articles/65972fe4e0894b

**Comment by hirom0922** [comment]
@ke158 @Ta23ka98 
FreezedとGeoFlutterFireとFireStore連携の件、
かなり、常夜灯（以前の共同開発？）のプロジェクトのソースを参考にしましたが、
位置情報は２階層で登録して、それに対する検索もできているぽいので
なるべく早くサンプルとスキーマ定義をあげようかと思います。

結構、まだ散らかっているので、、
けーさんの方でうまくいってそうでしたら、先に上げていただいても大丈夫です。



<img width="575" alt="image" src="https://user-images.githubusercontent.com/90263627/201502620-92ab1b2b-af8e-4569-b04b-49f371567251.png">

<img width="229" alt="image" src="https://user-images.githubusercontent.com/90263627/201502669-f44c93de-81d2-4302-b26c-8ff03cede35b.png">

**Comment by Ta23ka98** [comment]
hiromさんのスキーム定義の最終案ですが、一応載せておいてクローズします🙋

```
users: #collection
  documentId: # userId = auth.uid
    id: string # documentId
    userName: string
    selfIntroduction: string
    profileImageURL: string
    createdAt: timestamp

posts: #collection
  documentId: # auto
    id: string # documentId
    postUserRef: reference
    postImageURL: string
    title: string
    content: string
    postPosition:
      geohash: string
      geopoint: geopoint
    likeCount: number
    createdAt: timestamp

userLikes: #collection
  documentId: # auto
    id: string # documentId
    userRef: reference
    postRef: reference
    createdAt: timestamp
```
